config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'pages#home'
  get 'howto' => 'pages#howto'
  get 'contact' => 'pages#contact'
  get 'cookie' => 'pages#cookie'
  get 'terms' => 'pages#terms'
  get 'privacy' => 'pages#privacy'
  get 'signup' => 'users#new'
  get '/users/:id/practice' => 'users#practice', as: :practice
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :practices, only: [:create]
  
    

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    before_action :get_user, only: [:edit, :update]
    before_action :valid_user, only: [:edit, :update]
    before_action :check_expiration, only: [:edit, :update]
  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
      if @user
          @user.create_reset_digest
          @user.send_password_reset_email
          flash[:info] = "Email sent with password reset instructions"
          redirect_to root_url
      else
          flash.now[:danger] = "Email address not found"
          render 'new'
      end
  end
    
  def edit
  end
    
  def update
    if password_blank?
        flash.now[:danger] = "Password can't be blank."
        render 'edit'
    elsif @user.update_attributes(user_params)
            log_in @user
        flash[:success] = "Password has been reset."
        redirect_to @user
    else
        render 'edit'
    end
  end
    
  private
    def user_params
        params.require(:user).permit(:password, :password_confirmation)
    end
    
    def password_blank?
        params[:user][:password].blank?
    end
    
    def get_user
        @user = User.find_by(email: params[:email])
    end
    
    #confirms a valid user
    def valid_user
        unless(@user && @user.activated?)
            redirect_to root_url
        end
    end
    
    def check_expiration
        if @user.password_reset_expired?
            flash[:danger] = "Password reset has expired"
            redirect_to new_password_reset_url
        end
    end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, 'Reset password') %>     

            <div class="bg">
</div>

<!--SIGNUP START-->
<div class="container">
    	<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="panel panel-login">
					<div class="panel-heading">
						<div class="row">
							<div class="col-xs-12">
								<a class="active" href="#" id="login-form-link"><h1>Reset password</h1></a>
							</div>
						</div>
						<hr>
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-12">
                                
                                    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
                                <%= render 'shared/error_messages', object: f.object %>
									<div class="form-group">
                                        <%= hidden_field_tag :email, @user.email %>
										
									</div>
									<div class="form-group">
                                        <%= f.password_field :password, class: 'form-control', placeholder:"Password" %>
										
									</div>
                                	<div class="form-group">
<%= f.password_field :password_confirmation, class: 'form-control', placeholder:"Confirm Password" %>						
									</div>
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
					<%= f.submit "Update password", class: "form-control btn btn-login" %>		
											</div>
										</div>
									</div>
                                <% end %>
										</div>
									</div>
								

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

app/views/password_resets/new.html.erb
<% provide(:title, 'Forgot password') %>     

            <div class="bg">
</div>

<!--SIGNUP START-->
<div class="container">
    	<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="panel panel-login">
					<div class="panel-heading">
						<div class="row">
							<div class="col-xs-12">
								<a class="active" href="#" id="login-form-link"><h1>Forgot password</h1></a>
							</div>
						</div>
						<hr>
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-12">
                                
                                    <%= form_for(:password_reset, url: password_resets_path) do |f| %>
									<div class="form-group">
                                        <%= f.email_field :email, class: 'form-control', placeholder:"Email" %>
										
									</div>

									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
					<%= f.submit "Submit", class: "form-control btn btn-login" %>		
											</div>
										</div>
									</div>

								<% end %>

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>