config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'pages#home'
  get 'howto' => 'pages#howto'
  get 'contact' => 'pages#contact'
  get 'cookie' => 'pages#cookie'
  get 'terms' => 'pages#terms'
  get 'privacy' => 'pages#privacy'
  get 'signup' => 'users#new'
  get '/users/:id/practice' => 'users#practice', as: :practice
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :practices, only: [:create]
  
    

end

app/views/pages/contact.html.erb
<% provide(:title, "Contact") %> 
<div class="background-pic7">
</div>
<div class="container fitme">
    <div class="row">
        <div class="col-md-8 col-md-offset-2 contact">
            <h1>About Me</h1>
            <p>I plan to continually update the app to make it better.  Any feedback that you could think of would be of amazing help. Lets build this app together!</p>
        </div>
  
        <div class="col-md-8 col-md-offset-2 contact1">
          <h1>Contact</h1>
                <i class="fa fa-envelope fa-inverse fa-5x"></i>
            <br>
          <a href="myhoopstats@gmail.com">myhoopstats@gmail.com</a>
        </div>
        <div class="col-md-12 ">
        <footer class="footer">
  <small>
    <%= link_to "MyHoopStats", root_url %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Terms of Service",  terms_path %></li>
      <li><%= link_to "Cookie Policy",   cookie_path %></li>
      <li><%= link_to "Privacy Policy", privacy_path %></li>
    </ul>
  </nav>
</footer>
        </div>
    </div>
</div>

app/views/pages/cookie.html.erb
<% provide(:title, "Cookie Policy") %> 
<div class="container">
<h1>MyHoopStats COOKIES POLICY</h1>

<h3>Credit</h3>

    <p>This document was created using a Contractology template available at http://www.freenetlaw.com.</p>

<h3>About cookies</h3>

<p>This website uses cookies.  By using this website and agreeing to this policy, you consent to MyHoopStats's use of cookies in accordance with the terms of this policy.</p>

<p>Cookies are files sent by web servers to web browsers, and stored by the web browsers.</p> 

<p>The information is then sent back to the server each time the browser requests a page from the server.  This enables a web server to identify and track web browsers.</p> 

<p>There are two main kinds of cookies: session cookies and persistent cookies.  Session cookies are deleted from your computer when you close your browser, whereas persistent cookies remain stored on your computer until deleted, or until they reach their expiry date.</p>

    <h3>Google cookies</h3>

<p>MyHoopStats uses Google Analytics to analyse the use of this website.  Google Analytics generates statistical and other information about website use by means of cookies, which are stored on users' computers.  The information generated relating to our website is used to create reports about the use of the website. Google will store and use this information.  Google's privacy policy is available at: http://www.google.com/privacypolicy.html.]</p>


<p>Most browsers allow you to refuse to accept cookies.</p>  

<p>In Internet Explorer, you can refuse all cookies by clicking “Tools”, “Internet Options”, “Privacy”, and selecting “Block all cookies” using the sliding selector.</p>  

<p>In Firefox, you can adjust your cookies settings by clicking “Tools”, “Options” and “Privacy”.</p>

<p>Blocking cookies will have a negative impact upon the usability of some websites.</p>

</div>
    <div class="container">
<footer class="footer">
  <small>
    <%= link_to "MyHoopStats", root_url %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Terms of Service",  terms_path %></li>
      <li><%= link_to "Cookie Policy",   cookie_path %></li>
      <li><%= link_to "Privacy Policy", privacy_path %></li>
    </ul>
  </nav>
</footer>
    </div>

app/views/pages/home.html.erb
<div class="background-pic">
</div>    
<!-- Main jumbotron -->
    <header>
        <div class="header-content">
            <div class="header-content-inner">
            <div>MyHoopStats</div>
                        
                <%= image_tag("logo1.png") %>
                <p>The greatest shooters are great because they shoot a lot of shots. Ray Allen shoots around 300 shots before every game. Science has proven that the best way to improve is to set goals and track your progress. MyHoopStats aims to provide you with the means to track your stats using voice commands, set goals and see your progress over time</p>
            <% if logged_in? %>
              <% else %>
            <%= link_to "Sign up", signup_path, class: "btn btn-primary btn-xl page-scroll btns" %>
                <% end %>
            </div>
        </div>
    </header>

<!--Informational row-->
    <div class="container ycontainer">
      <div class="row">
          <div class="col-md-6">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <h2>Track Stats</h2>
                <span class="fa-stack fa-3x">
                    <i class="fa fa-square fa-stack-2x"></i>
                    <i class="fa fa-line-chart fa-stack-1x fa-inverse"></i>
                </span>
                <p>Use MyHoopStats to track your free throw and field goal percentage overtime and set goals to improve your performance.</p>              
            </div>
            <div class="col-lg-12 col-md-12">
                <h2>Voice Activated</h2>
                <span class="fa-stack fa-3x">
                    <i class="fa fa-square fa-stack-2x"></i>
                    <i class="fa fa-microphone fa-stack-1x fa-inverse"></i>
                </span>    
                <p>For Android users, use simple voice commands to track your progress.</p>
            </div>
            <div class="col-lg-12 col-md-12">
                <h2>Web App</h2>
                <span class="fa-stack fa-3x">
                    <i class="fa fa-square fa-stack-2x"></i>
                    <i class="fa fa-mobile fa-stack-1x fa-inverse fa-1x"></i>
                </span>
                <p>Simply access MyHoopStats on your phones web browser and track whether you are at the gym or the park.</p>
            </div>
          </div>
          <div class="col-md-6 col-sm-12">
            <%= video_tag(["features.mov","features.mp4"], controls: true, size: "350x510") %>
          </div>
      </div>
    </div> 
<!-- /ycontainer -->

<!--Contact row-->
    <div class="container xcontainer">
      <div class="row">
        <div class="col-md-12">
          <h2>Contact Us</h2>
            <span class="fa-stack fa-4x">
                <i class="fa fa-square fa-stack-2x"></i>
                <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
            </span><br>
          <a href="myhoopstats@gmail.com">myhoopstats@gmail.com</a>
        </div>
      </div>
    </div> 
<!-- /xcontainer --> 

<!--Footer row-->
    <div class="container">
        <footer class="footer">
            <small>
                <%= link_to "MyHoopStats", root_url %>
            </small>
        <nav>
            <ul>
                <li><%= link_to "Terms of Service",  terms_path %></li>
                <li><%= link_to "Cookie Policy",   cookie_path %></li>
                <li><%= link_to "Privacy Policy", privacy_path %></li>
            </ul>
        </nav>
        </footer>
    </div>

app/views/pages/howto.html.erb
<% provide(:title, 'How To') %>
<div class="background-pic7">
</div>    
<!-- Main jumbotron -->
<div class="container fitme">
    <div class="row howto">
        <div class="col-lg-6 col-md-6 col-sm-12">
            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Basics
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <ul>
            <li>Choose Free Throw or Jump Shot</li>
            <li>Use Touch or Voice commands to log shots</li>
            <li>Save data</li>
            <li>Head to the Dashboard to see your progress</li>
        </ul>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Voice Commands
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
        If you have an Android phone, allow MyHoopStats to access your microphone and use voice commands to track your progress. <br><br>All voice commands are located on the buttons: <br>
        <ul>
            <li>Say "free throw" or "jump shot" to choose what to track</li>
            <li>Say "make" or "miss" to log shots</li>
            <li>Say "save" to save your results</li>
        </ul>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Acronyms
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
        <ul>
            <li>FGA - Field Goal Attempts</li>
            <li>FG% - Field Goal Percentage</li>
            <li>FTA - Free Throw Attempts</li>
            <li>FT% - Free Throw Percentage</li>
        </ul>
      </div>
    </div>
  </div>
</div>
</div>
        <div class="col-md-6 col-sm-12 video">
            <%= video_tag(["Practice.mov","Practice.mp4"], controls: true, size: "350x450") %>
        </div>
    </div>
</div> 

app/views/pages/privacy.html.erb
<% provide(:title, 'Privacy Policy') %>
<div class="container">
<h1>MyHoopStats Privacy Policy</h1>
<p>

This privacy policy discloses the privacy practices for MyHoopStats.com. This privacy policy applies solely to information collected by this web site. It will notify you of the following:
<ul>
<li>What personally identifiable information is collected from you through the web site, how it is used and with whom it may be shared.</li>
<li>What choices are available to you regarding the use of your data.
<li>The security procedures in place to protect the misuse of your information.</li>
<li>How you can correct any inaccuracies in the information.</li>
<li>Information Collection, Use, and Sharing</li> 
</ul>

We are the sole owners of the information collected on this site. We only have access to/collect information that you voluntarily give us via email or other direct contact from you. We will not sell or rent this information to anyone.

We will use your information to respond to you, regarding the reason you contacted us. We will not share your information with any third party outside of our organization, other than as necessary to fulfill your request.

Unless you ask us not to, we may contact you via email in the future to tell you about specials, new products or services, or changes to this privacy policy.

Your Access to and Control Over Information 
You may opt out of any future contacts from us at any time. You can do the following at any time by contacting us via the email address given on our website:

   • See what data we have about you, if any.

   • Change/correct any data we have about you.

   • Have us delete any data we have about you.

   • Express any concern you have about our use of your data.

<h3>Security</h3> 
We take precautions to protect your information. When you submit sensitive information via the website, your information is protected both online and offline.

Wherever we collect sensitive information (such as an account password), that information is encrypted and transmitted to us in a secure way. You can verify this by looking for a closed lock icon at the beginning of your address bar or looking for "https" at the beginning of the address of the web page.

While we use encryption to protect sensitive information transmitted online, we also protect your information offline. Only employees who need the information to perform a specific job are granted access to personally identifiable information. The computers/servers in which we store personally identifiable information are kept in a secure environment.

Updates

Our Privacy Policy may change from time to time and all updates will be posted on this page.

If you feel that we are not abiding by this privacy policy, you should contact us immediately via email.</p>

</div>
    <div class="container">
<footer class="footer">
  <small>
    <%= link_to "MyHoopStats", root_url %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Terms of Service",  terms_path %></li>
      <li><%= link_to "Cookie Policy",   cookie_path %></li>
      <li><%= link_to "Privacy Policy", privacy_path %></li>
    </ul>
  </nav>
</footer>
    </div>

app/views/pages/terms.html.erb
<% provide(:title, "Terms") %> 
<div class="container">

<h1>MyHoopStats TERMS AND CONDITIONS</h1>


<h3>Credit</h3>

<p>This document was created using a Contractology template available at http://www.freenetlaw.com.</p>

<h3>Introduction</h3>

<p>These terms and conditions govern your use of this website; by using this website, you accept these terms and conditions in full.   If you disagree with these terms and conditions or any part of these terms and conditions, you must not use this website.</p> 

<p>[You must be at least [18] years of age to use this website.  By using this website [and by agreeing to these terms and conditions] you warrant and represent that you are at least [18] years of age.]</p>

<p>[This website uses cookies.  By using this website and agreeing to these terms and conditions, you consent to MyHoopStats's use of cookies in accordance with the terms of MyHoopStats's <%= link_to "Cookie Policy",   cookie_path %> and <%= link_to "Privacy Policy", privacy_path %>.</p>

<h3>License to use website</h3>

<p>Unless otherwise stated, MyHoopStats and/or its licensors own the intellectual property rights in the website and material on the website.  Subject to the license below, all these intellectual property rights are reserved.</p>

<p>You may view, download for caching purposes only, and print pages from the website for your own personal use, subject to the restrictions set out below and elsewhere in these terms and conditions. </p> 

<p>You must not:
<ul>
<li>republish material from this website (including republication on another website);</li>
<li>sell, rent or sub-license material from the website;</li>
<li>show any material from the website in public;</li>
<li>reproduce, duplicate, copy or otherwise exploit material on this website for a commercial purpose;</li>
<li>edit or otherwise modify any material on the website; or</li>
<li>[redistribute material from this website [except for content specifically and expressly made available for redistribution].</li>
</ul>
    </p>

<h3>Acceptable use</h3>

<p>You must not use this website in any way that causes, or may cause, damage to the website or impairment of the availability or accessibility of the website; or in any way which is unlawful, illegal, fraudulent or harmful, or in connection with any unlawful, illegal, fraudulent or harmful purpose or activity.</p>

<p>You must not use this website to copy, store, host, transmit, send, use, publish or distribute any material which consists of (or is linked to) any spyware, computer virus, Trojan horse, worm, keystroke logger, rootkit or other malicious computer software.</p>

<p>You must not conduct any systematic or automated data collection activities (including without limitation scraping, data mining, data extraction and data harvesting) on or in relation to this website without MyHoopStats express written consent.</p>

<p>You must not use this website to transmit or send unsolicited commercial communications.</p>

You must not use this website for any purposes related to marketing without MyHoopStats express written consent. </p> 

<h3>Restricted access</h3>

<p>Access to certain areas of this website is restricted.  MyHoopStats reserves the right to restrict access to [other] areas of this website, or indeed this entire website, at MyHoopStats discretion.</p>

<p>If MyHoopStats provides you with a user ID and password to enable you to access restricted areas of this website or other content or services, you must ensure that the user ID and password are kept confidential.</p>  

<p></p>MyHoopStats may disable your user ID and password in MyHoopStats's sole discretion without notice or explanation.</p>

<h3>User content</h3>

<p>In these terms and conditions, “your user content” means material (including without limitation text, images, audio material, video material and audio-visual material) that you submit to this website, for whatever purpose.</p>

<!--You grant to MyhoopStats a worldwide, irrevocable, non-exclusive, royalty-free license to use, reproduce, adapt, publish, translate and distribute your user content in any existing or future media.  You also grant to [NAME] the right to sub-license these rights, and the right to bring an action for infringement of these rights.-->

<p>Your user content must not be illegal or unlawful, must not infringe any third party's legal rights, and must not be capable of giving rise to legal action whether against you or MyHoopStats or a third party (in each case under any applicable law).</p>  

<p>You must not submit any user content to the website that is or has ever been the subject of any threatened or actual legal proceedings or other similar complaint.</p>

<p>MyHoopStats reserves the right to edit or remove any material submitted to this website, or stored on MyHoopStats's servers, or hosted or published upon this website.</p>

<p>Notwithstanding MyHoopStats's rights under these terms and conditions in relation to user content, MyHoopStats does not undertake to monitor the submission of such content to, or the publication of such content on, this website.]</p>

<h3>No warranties</h3>

<p>This website is provided “as is” without any representations or warranties, express or implied.  MyHoopStats makes no representations or warranties in relation to this website or the information and materials provided on this website.</p>  

<p>Without prejudice to the generality of the foregoing paragraph, MyHoopStats does not warrant that:
<ul>
<li>this website will be constantly available, or available at all; or</li>
<li>the information on this website is complete, true, accurate or non-misleading.</li>
</ul>
</p>

<h3>Limitations of liability</h3>

<p>MyHoopStats will not be liable to you (whether under the law of contact, the law of torts or otherwise) in relation to the contents of, or use of, or otherwise in connection with, this website:
<ul>
<li>to the extent that the website is provided free-of-charge, for any direct loss;</li>
<li>for any indirect, special or consequential loss; or</li>
<li>for any business losses, loss of revenue, income, profits or anticipated savings, loss of contracts or business relationships, loss of reputation or goodwill, or loss or corruption of information or data.</li></ul></p>

<p>These limitations of liability apply even if MyHoopStats has been expressly advised of the potential loss.</p>

<h3>Exceptions</h3>

<p>Nothing in this website disclaimer will exclude or limit any warranty implied by law that it would be unlawful to exclude or limit; and nothing in this website disclaimer will exclude or limit MyHoopStats's liability in respect of any:
<ul>
<li>death or personal injury caused by MyHoopStats's negligence;</li>
<li>fraud or fraudulent misrepresentation on the part of MyHoopStats; or</li>
<li>matter which it would be illegal or unlawful for MyHoopStats to exclude or limit, or to attempt or purport to exclude or limit, its liability.</li>
    </ul>
</p>
<h3>Reasonableness</h3>

<p>By using this website, you agree that the exclusions and limitations of liability set out in this website disclaimer are reasonable.</p>  

<p>If you do not think they are reasonable, you must not use this website.</p>

<!--
Other parties

[You accept that, as a limited liability entity, [NAME] has an interest in limiting the personal liability of its officers and employees.  You agree that you will not bring any claim personally against [NAME'S] officers or employees in respect of any losses you suffer in connection with the website.]

[Without prejudice to the foregoing paragraph,] you agree that the limitations of warranties and liability set out in this website disclaimer will protect [NAME'S] officers, employees, agents, subsidiaries, successors, assigns and sub-contractors as well as [NAME]. 
-->

<h3>Unenforceable provisions</h3>

<p>If any provision of this website disclaimer is, or is found to be, unenforceable under applicable law, that will not affect the enforceability of the other provisions of this website disclaimer.</p>

<h3>Indemnity</h3>

<p>You hereby indemnify MyHoopStats and undertake to keep MyHoopStats indemnified against any losses, damages, costs, liabilities and expenses (including without limitation legal expenses and any amounts paid by MyHoopStats to a third party in settlement of a claim or dispute on the advice of MyHoopStats legal advisers) incurred or suffered by MyHoopStats arising out of any breach by you of any provision of these terms and conditions, or arising out of any claim that you have breached any provision of these terms and conditions.</p>

<h3>Breaches of these terms and conditions</h3>

<p>Without prejudice to MyHoopStats's other rights under these terms and conditions, if you breach these terms and conditions in any way, MyHoopStats may take such action as MyHoopStats deems appropriate to deal with the breach, including suspending your access to the website, prohibiting you from accessing the website, blocking computers using your IP address from accessing the website, contacting your internet service provider to request that they block your access to the website and/or bringing court proceedings against you.</p>

<h3>Variation</h3>

<p>MyHoopStats may revise these terms and conditions from time-to-time.  Revised terms and conditions will apply to the use of this website from the date of the publication of the revised terms and conditions on this website.  Please check this page regularly to ensure you are familiar with the current version.</p>

<h3>Assignment</h3>

</p>MyHoopStats may transfer, sub-contract or otherwise deal with [NAME'S] rights and/or obligations under these terms and conditions without notifying you or obtaining your consent.</p>

<p>You may not transfer, sub-contract or otherwise deal with your rights and/or obligations under these terms and conditions.</p>  

<h3>Severability</h3>

<p>If a provision of these terms and conditions is determined by any court or other competent authority to be unlawful and/or unenforceable, the other provisions will continue in effect.  If any unlawful and/or unenforceable provision would be lawful or enforceable if part of it were deleted, that part will be deemed to be deleted, and the rest of the provision will continue in effect.</p> 

<h3>Entire agreement</h3>

<p>These terms and conditions [, together with [DOCUMENTS],] constitute the entire agreement between you and MyHoopStats in relation to your use of this website, and supersede all previous agreements in respect of your use of this website.</p>

<h3>Law and jurisdiction</h3>

<p>These terms and conditions will be governed by and construed in accordance with [GOVERNING LAW], and any disputes relating to these terms and conditions will be subject to the [non-]exclusive jurisdiction of the courts of [JURISDICTION].</p>

<!--
[Registrations and authorisations

[[NAME] is registered with [TRADE REGISTER].  You can find the online version of the register at [URL].  [NAME'S] registration number is [NUMBER].]</p>

[[NAME] is subject to [AUTHORISATION SCHEME], which is supervised by [SUPERVISORY AUTHORITY].]</p>

[[NAME] is registered with [PROFESSIONAL BODY].  [NAME'S] professional title is [TITLE] and it has been granted in the United Kingdom.  [NAME] is subject to the [RULES] which can be found at [URL].]

[[NAME] subscribes to the following code[s] of conduct: [CODE(S) OF CONDUCT].  [These codes/this code] can be consulted electronically at [URL(S)].

[[NAME'S] [TAX] number is [NUMBER].]]

[NAME'S] details

The full name of [NAME] is [FULL NAME].  

[[NAME] is registered in [JURISDICTION] under registration number [NUMBER].]  

[NAME'S] [registered] address is [ADDRESS].  

You can contact [NAME] by email to [EMAIL].
-->

</div>
    <div class="container">
<footer class="footer">
  <small>
    <%= link_to "MyHoopStats", root_url %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Terms of Service",  terms_path %></li>
      <li><%= link_to "Cookie Policy",   cookie_path %></li>
      <li><%= link_to "Privacy Policy", privacy_path %></li>
    </ul>
  </nav>
</footer>
    </div>