config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'pages#home'
  get 'howto' => 'pages#howto'
  get 'contact' => 'pages#contact'
  get 'cookie' => 'pages#cookie'
  get 'terms' => 'pages#terms'
  get 'privacy' => 'pages#privacy'
  get 'signup' => 'users#new'
  get '/users/:id/practice' => 'users#practice', as: :practice
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :practices, only: [:create]
  
    

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>

<!--MOBILE WEB APP OPTIMIZATION CODE-->
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="white-translucent">
    <meta name="mobile-web-app-capable" content="yes">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= favicon_link_tag '/logo1.ico' %>
    
</head>
<body>
    
<!--START OF CUSTOM NAV BAR-->
    
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <div class="navbar-brand brandlogo"><%= image_tag('logo1.png') %></div>
            <div class="navbar-brand brandname"><%= link_to(image_tag('brand-name.png'), root_path) %></div>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <% if logged_in? %>
            <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Dashboard", current_user %></li>
            <li><%= link_to "Practice", practice_path(current_user) %></li>
<!--            <li><%= link_to "Game", '#' %></li>-->
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %><span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
               <% if current_user.admin %>
                <li><%= link_to "All users", users_path %></li>
                <% else %><% end %>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "How To", howto_path %></li>
                <li><%= link_to "Contact", contact_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                                </ul>
                </li>
          </ul>
            <% else %>
            
          <ul class="nav navbar-nav navbar-right">

              <li><%= link_to "Sign up", signup_path %></li>
              
              <li><%= link_to "Log in", login_path %></li>
          </ul>
 <% end %>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>
<!--END OF CUSTOM NAV BAR    -->

<!--flash successful signup message start-->
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

<!--flash successful signup message end-->

<%= yield %>
    

    <%= javascript_include_tag 'app.js' %>
    <%= javascript_include_tag 'mobiletouch.js' %>
    <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
   

<!--<%= debug(params) if Rails.env.development? %>-->
</body>
</html>